### ISSUE TITLE
FIFOQueue '_1_input_reader/batch/fifo_queue' is closed and has insufficient elements (requested 1, current size 0)

### ISSUE THREAD

**Issue by dorp92** [CVLAB-Unibo/Real-time-self-adaptive-deep-stereo#1]
Hi,
I am trying to run the Stereo_Online_Adaptation script with the following arguments:

> python Stereo_Online_Adaptation.py -l ~/Desktop/deep-stereo/data/kitti/list.txt -o ~/Desktop/deep-stereo/outputs --weights ~/Desktop/deep-stereo/pretrained/MADNet/kitti/weights.ckpt --modelName MADNet --blockConfig ~/Desktop/deep-stereo/block_config/MadNet_full.json --mode MAD --sampleMode PROBABILITY 

The first row of list.txt looks like this:

> /home/dp92/Desktop/deep-stereo/data/kitti/image_02/data/0000000000.png,/home/dp92/Desktop/deep-stereo/data/kitti/image_03/data/0000000000.png,/home/dp92/Desktop/deep-stereo/data/kitti/image_00/data/0000000000.png

I am using `/home/dp92/Desktop/deep-stereo/data/kitti/image_00/data/0000000000.png` as fake GT, is it OK? or how should it run it without GT?  
Anyway the process is not completed successfully, What could be the problem?
Full log:
https://pastebin.com/TJmcDH81

**Comment by AlessioTonioni** [comment]
> I am using /home/dp92/Desktop/deep-stereo/data/kitti/image_00/data/0000000000.png as fake GT, is it OK? or how should it run it without GT?
Yes, it is ok. The GT is only used for evaluation purpose, not for the actual algorithm. Just be sure that the GT you are loading is a 1 channel image (either 8 or 16 bit) and with the same resolution as the left and right frames.

> Anyway the process is not completed successfully, What could be the problem?

With newer versions of tensorflow, the try-except block I was using is not properly catching all the exceptions, and when all the image are elaborated the background thread raise an exception.
 
Looking at your log it might have completed the execution just fine, check if in '~/Desktop/deep-stereo/outputs' there is a file called 'series.csv', it should display one row with some info for each image elaborated. 
Moreover, if you run the same script with the additional command line option '--logDispStep 1' it should save in the output folder the disparity predicted by the network.

Apologize for the poor exception handling, I'll improve the code soon.

**Comment by dorp92** [comment]
Thanks! After have added the  '--logDispStep 1' option I got the disparity predictions.
I would suggest to add this option to the readme page.
