### ISSUE TITLE
Input and output tensor names for inference using pretrained model

### ISSUE THREAD

**Issue by Eeppii** [CVLAB-Unibo/Real-time-self-adaptive-deep-stereo#10]
Thanks for sharing the code of your interesting work! I would like to run the pretrained MADNet model within my C++ project. I can successfully load the checkpoint of the provided pretrained model. However, to run the inference session using the tensorflow C++ API I need to know the exact names of the input and the output tensors.

In the code I found "left_img" and "right_img" to be the placeholders for the input images and the last layer added to the disparities is named "rescaled_prediction". However, using those names as input/output tensor names results in errors indicating I'm not using the correct tensor names.

May I ask what the correct tensor names are for an inference from raw-images to the highest quality disparity?

Thanks a lot!

**Comment by AlessioTonioni** [comment]
The graph defined in `Stereo_Online_Adaptation.py` does not define placeholders and it is not meant for live inference. 
To use the network on C++ I think it would be better to write a new minimal python script with proper placeholders for the input tensor and then freeze that graph.
See issue #5

**Comment by Eeppii** [comment]
Thanks for the fast help!
As you suggested, I created a python script similar to #5 to define my own input tensor names. Inspecting the graph I found that the last output layer is named "model/resize_image_with_crop_or_pad_1/control_dependency_3:0".
Using the above tensor names I was able to run the network on live data in C++.
Thanks again!
