### ISSUE TITLE
 _make_disp() missing 1 required positional argument: 'scale'  line50, in DispNet.py

### ISSUE THREAD

**Issue by AnushaManila** [CVLAB-Unibo/Real-time-self-adaptive-deep-stereo#11]

**Comment by AnushaManila** [comment]
line 50: self._disparities.append(self._make_disp(self._layers[name + '/predict']))
Isn't a second parameter 'scale' missing here?

**Comment by AlessioTonioni** [comment]
You are right, sorry!
I forgot to push the last commit. 
It should be fixed now.

**Comment by AnushaManila** [comment]
Thanks for the update!
