### ISSUE TITLE
disparity converting script on kitti

### ISSUE THREAD

**Issue by meteorshowers** [CVLAB-Unibo/Real-time-self-adaptive-deep-stereo#12]
Great work!
could you share your the disparity converting script on kitti？
Thanks a lot！
xuanyili.edu@gmail.com

**Comment by meteorshowers** [comment]
I find that the camera parameters in kitti is different in different subset.
baseline = 54cm
f = 718,9 pixels?
dose it right? or f = 721 or anything else?
Thanks

**Comment by AlessioTonioni** [comment]
The focals for the different days should be:
```
focal_map = {
    &apos;2011_09_26&apos;: 7.215377e+02,
    &apos;2011_09_28&apos;: 7.070493e+02,
    &apos;2011_09_29&apos;: 7.183351e+02,
    &apos;2011_09_30&apos;: 7.070912e+02,
    &apos;2011_10_03&apos;: 7.188560e+02
}
baseline = 0.54
```

**Comment by meteorshowers** [comment]
depth = 718*0.54/disparity
depth: m
disparity: pixel
if the disparity=1
then the depth = 718*0.54 = 387.72 m
if the disparity=192
the lowest depth is 718*0.54/192 = 2.02 m
Am I right?
Do you  just use this function to get the disparity map?
Thanks

**Comment by AlessioTonioni** [comment]
yes
