### ISSUE TITLE
May I ask where can I find the groundtruth images?

### ISSUE THREAD

**Issue by zuanshiyuanbao** [CVLAB-Unibo/Real-time-self-adaptive-deep-stereo#13]
I did not find the ground truth images on Kitti website.

**Comment by AlessioTonioni** [comment]
You can find the gt we used for evaluation here:
http://www.cvlibs.net/datasets/kitti/eval_depth.php?benchmark=depth_prediction

The downloaded data are depth maps that need to be transformed into disparity be using the focal length of the camera and the baseline.

**Comment by zuanshiyuanbao** [comment]
Thanks so much!
