### ISSUE TITLE
Got disp_image cropped

### ISSUE THREAD

**Issue by vigneshgig** [CVLAB-Unibo/Real-time-self-adaptive-deep-stereo#17]
this input image
![view_right](https://user-images.githubusercontent.com/34392627/61575639-d50dd200-aaeb-11e9-9863-caf1b3f11513.png)
![view_left](https://user-images.githubusercontent.com/34392627/61575640-d50dd200-aaeb-11e9-8e5a-f3b4c7146f43.png)

output image
![disparity_0](https://user-images.githubusercontent.com/34392627/61575642-e1922a80-aaeb-11e9-89d5-c113b8ba6885.png)

output image is cropped

command

python3 Stereo_Online_Adaptation_edit.py     -l ./image_list.csv     -o ./output     --weights ./pretrained_nets/MADNet/kitti/weights.ckpt     --modelName MADNet     --blockConfig "block_config/MadNet_full.json"     --mode FULL     --sampleMode PROBABILITY --logDispStep 1

**Comment by AlessioTonioni** [comment]
You should feed the proper value to the `--imageShape` flag.
