### ISSUE TITLE
how can we convert the output disparsity image  into real world depth in any camera and environment.

### ISSUE THREAD

**Issue by vigneshgig** [CVLAB-Unibo/Real-time-self-adaptive-deep-stereo#18]
how can we convert the disparsity image  to real world depth into any camera and environment.

one more question, is getting out image is disparsity image or  depth image.

**Comment by mattpoggi** [comment]
Hello @vigneshgig ,
the network produces disparity maps since it runs stereo matching between left and right images.
You can obtain depth by knowing the focal length and baseline of the stereo camera as follows:
depth = focal * baseline / disparity

**Comment by vigneshgig** [comment]
thanks for reply

**Comment by vigneshgig** [comment]
can you 

> Hello @vigneshgig ,
> the network produces disparity maps since it runs stereo matching between left and right images.
> You can obtain depth by knowing the focal length and baseline of the stereo camera as follows:
> depth = focal * baseline / disparity

can you tell me the unit for baseline ,focal and disparity unit get from the output
when I given baseline 113 in mm  and focal length got from opencv stereo intrinsic parameter for that I dont know the unit. I getting some what good disparity image getting but when I converting the disparity to depth I am getting some weird pattern in the depth.
I think it may be unit problem when i dividing the baseline and focal length by disparity

**Comment by mattpoggi** [comment]
Hi @vigneshgig ,
after triangulation, you have depth in the same unit of your baseline, e.g. if you use 113 mm, you will obtain depth in mm, probably overflowing the colormap range. I would use baseline in meters (0.113) to have better visualization.

**Comment by vigneshgig** [comment]
> Hi @vigneshgig ,
> after triangulation, you have depth in the same unit of your baseline, e.g. if you use 113 mm, you will obtain depth in mm, probably overflowing the colormap range. I would use baseline in meters (0.113) to have better visualization.

after changing the 113 to 0.113 I am getting only blue screen no changes in depth screen
baseline = 0.113
focal_length = 761.501486
depth = focal_length * baseline / disp_prediction[0]

**Comment by AlessioTonioni** [comment]
`cv2.applyColorMap` applies a color map assuming of having values evenly spreaded between 0 and 255. If you use 0.113 as baseline the depth you will get will be expressed in m, therefore the colormap you are applying would remap a pixel at 0m as deep blue, a pixel at 255m as deep red. Try to properly normalize the value according to your range of interest before applying the colormap and you should see more colors.
