### ISSUE TITLE
how to use custom camera in Live Demo

### ISSUE THREAD

**Issue by vigneshgig** [CVLAB-Unibo/Real-time-self-adaptive-deep-stereo#19]
how to use DIY stereo camer like below example
https://erget.files.wordpress.com/2014/02/img_20140131_114640-resized.jpg
how to connect two separate webcam as a stereo in Live_Adaptation_Demo.py any idea

Thanks

**Comment by AlessioTonioni** [comment]
Hi,
Concerning the software you just need to write a wrapper to acquire frames from the two cameras. See `Grabber.py` for some example of camera grabber. 
From a more practical point of view you have first to synchronize the two cameras and calibrate the stereo system such that you can then feed the network with rectified stereo frames.
