### ISSUE TITLE
failed to load pretrained weights

### ISSUE THREAD

**Issue by Lvhhhh** [CVLAB-Unibo/Real-time-self-adaptive-deep-stereo#20]
failed to load pretrained weights
here is the error:
Traceback (most recent call last):
  File "/home/lvhao/MADNet/Stereo_Online_Adaptation.py", line 324, in <module>
    main(args)
  File "/home/lvhao/MADNet/Stereo_Online_Adaptation.py", line 150, in main
    var_to_restore = weights_utils.get_var_to_restore_list(args.weights, [])
  File "/home/lvhao/MADNet/Data_utils/weights_utils.py", line 27, in get_var_to_restore_list
    reader = tf.train.NewCheckpointReader(ckpt_path)
  File "/home/lvhao/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 636, in NewCheckpointReader
    return CheckpointReader(compat.as_bytes(filepattern))
  File "/home/lvhao/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 648, in __init__
    this = _pywrap_tensorflow_internal.new_CheckpointReader(filename)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Unsuccessful TensorSliceReader constructor: Failed to get matching files on  /home/lvhao/MADNet/MADNet/synthetic/weights.ckpt: Not found:  /home/lvhao/MADNet/MADNet/synthetic; No such file or directory

Process finished with exit code 1

the directory "/home/lvhao/MADNet/MADNet/synthetic" is existed. and have  "weights.ckpt.data-00000-of-00001" "weights.ckpt.index" "weights.ckpt.meta" downloaded from your link.
how to solve it? thanks

**Comment by mattpoggi** [comment]
Hello @Lvhhhh ,
can you please paste the exact command you are running?
Thanks

**Comment by tianyilt** [comment]
I find that '.csv' matters. 1 Use Notepad to open csv file. 2 it must use , to split and end with ;  
the third picture should be deep-stereo（至少保证单通道）
example:       /data/depth_test/Real-time-self-adaptive-deep-stereo-master/dataset/training/image_2/000000_10.png,/data/depth_test/Real-time-self-adaptive-deep-stereo-master/dataset/training/image_3/000000_10.png,/data/depth_test/Real-time-self-adaptive-deep-stereo-master/dataset/training/disp_noc_1/000000_10.png

**Comment by tianyilt** [comment]
i rename "weights.ckpt.data-00000-of-00001" into "weights.ckpt"

**Comment by AlessioTonioni** [comment]
> I find that '.csv' matters. 1 Use Notepad to open csv file. 2 it must use , to split and end with ;
> the third picture should be deep-stereo（至少保证单通道）
> example: /data/depth_test/Real-time-self-adaptive-deep-stereo-master/dataset/training/image_2/000000_10.png,/data/depth_test/Real-time-self-adaptive-deep-stereo-master/dataset/training/image_3/000000_10.png,/data/depth_test/Real-time-self-adaptive-deep-stereo-master/dataset/training/disp_noc_1/000000_10.png

The extension of the file does not matter, you can use either `,` or `;` to separate path in the file. Make sure that you don'r have an empty blank line at the end of the file.

> i rename "weights.ckpt.data-00000-of-00001" into "weights.ckpt"

You should not do that, keep the file name as they are and use `weights.ckpt` as `--weights`, the tf library knows how to read the files...
