### ISSUE TITLE
About disparity_scale_factor for reprojection_loss

### ISSUE THREAD

**Issue by lcybuzz** [CVLAB-Unibo/Real-time-self-adaptive-deep-stereo#24]
In function `get_reprojection_loss`, there is
`disparity_scale_factor = tf.cast(tf.shape(current_disp)[2],tf.float32)/tf.cast(tf.shape(left)[2],tf.float32)`

However, in function `get_supervised_loss`, there is
`disparity_scale_factor = tf.cast(tf.shape(left)[2],tf.float32)/tf.cast(tf.shape(current_disp)[2],tf.float32)`

Shouldn't these two be the same? I think the second one maybe right. Thanks for any help!

**Comment by AlessioTonioni** [comment]
You are right, the second one is actually the right one, but in the current code both evaluate to 1 as the predictions are already rescaled to full resolution by the networks. Thank you for pointing it out I'll fix the implementation.
