### ISSUE TITLE
Poor performance using pretrained synthetic weights for both DispNet and MADNet

### ISSUE THREAD

**Issue by Deng-Y** [CVLAB-Unibo/Real-time-self-adaptive-deep-stereo#3]
I test the models (both DispNet and MADNet) on Flyingthing3D testset using the pretrained synthetic weights. I got poor performance:
DispNet: EPE=5.39, bad3=0.2255
MADNet: EPE=3.59, bad3=0.0833

According to DispNet paper, EPE of DispNet and DispNetCorr1D are 2.02 and 1.68 respectively.
Does anyone try this? What's your results? It won't take long too run the test since the testset is small.
Not sure whether it's because there are some bugs in my testing code or version differences in software packages or somehing else.

**Comment by AlessioTonioni** [comment]
Yes, the measured performances are correct. In the near future, I'm going to put online a script to train the network from scratch if you are able to improve the performance of the base model you are more than welcome.

**Comment by DengYon** [comment]
Thanks for your answer!

**Comment by AlessioTonioni** [comment]
Train.py provides a script to train the model from scratch
