### ISSUE TITLE
2 Questions about the correlation layer

### ISSUE THREAD

**Issue by XinjieInformatik** [CVLAB-Unibo/Real-time-self-adaptive-deep-stereo#30]
Hi @AlessioTonioni , thanks for sharing your work! I have a basic question. In the correlation layer, why the range is from -max_disp to max_disp, instead of from 0 to max_disp? Is it because of the pre-process method crop_padding? Is reduce_mean also used in original DispnetC?

```python 
def correlation_tf(x, y, max_disp, stride=1, name='corr'):
	with tf.variable_scope(name):
		corr_tensors = []
		y_shape = tf.shape(y)
		y_feature = tf.pad(y,[[0,0],[0,0],[max_disp,max_disp],[0,0]])
		for i in range(-max_disp, max_disp+1,stride):
			shifted = tf.slice(y_feature, [0, 0, i + max_disp, 0], [-1, y_shape[1], y_shape[2], -1])
			corr_tensors.append(tf.reduce_mean(shifted*x, axis=-1, keepdims=True))

		result = tf.concat(corr_tensors,axis=-1)
		return result
```

**Comment by AlessioTonioni** [comment]
> why the range is from -max_disp to max_disp, instead of from 0 to max_disp?

In the MadNet network design, the right feature at higher scales is warped according to the disparity predicted at lower scales. Since the lower scale prediction might be wrong we have to search across both directions for possible matches in order to recover mistakes and improve the predictions.

> Is reduce_mean also used in original DispnetC?

It should be

**Comment by XinjieInformatik** [comment]
Hi @AlessioTonioni , thanks for your clear answer!

**Comment by MeLonJ10** [comment]
Hi @AlessioTonioni, Does the correlation layer defined in this way mean that, it only use single pixel to calculate correlation rather than a patch centered at the candidate pixels?
Thank you so much!
