### ISSUE TITLE
Why not use a occlusion mask in the reconstruction loss?

### ISSUE THREAD

**Issue by sunshinnnn** [CVLAB-Unibo/Real-time-self-adaptive-deep-stereo#31]
Hi, I have a question. Although finding a occlusion mask is a bit difficult in the unsupervised learning,  but I think it masks sense as expressed in the picture below.
![image](https://user-images.githubusercontent.com/38182073/68543195-e5c1bb00-03ee-11ea-8316-9f202ec70544.png)

**Comment by AlessioTonioni** [comment]
Yes, it should improve the results. 
Feel free to modify the code to explicitly compute the occlusion mask and return it.
The code base is open to any pull request :)

**Comment by sunshinnnn** [comment]
Thanks for your reply.  ：）
