### ISSUE TITLE
How can I get the groundtruth data

### ISSUE THREAD

**Issue by wxw-matt** [CVLAB-Unibo/Real-time-self-adaptive-deep-stereo#32]
As the title mentioned, I am not sure how to get the ground-truth data.  
I think we need that for using Stereo_Online_Adaptation.py.

**Comment by AlessioTonioni** [comment]
The script uses ground-truth data only to compute performance metrics. You can safely use it feeding a mock image with all 0's as groundtruth.

**Comment by WZG3661** [comment]
You mean that even if  there isn't a groundtruth image, I have to give an image with all 0?

**Comment by AlessioTonioni** [comment]
yes, any image with the same resolution as the left and right one will work. The ground truth file is used only to compute performance.
