### ISSUE TITLE
Questions about residual refinement network

### ISSUE THREAD

**Issue by gallenszl** [CVLAB-Unibo/Real-time-self-adaptive-deep-stereo#33]
Hello, I have some questions about your residual refinement network.Can you tell me why you choose to concat disparity and left feature as input?Actually, it a little diffcult for me to understand why you seclect to concat two things which represent totally different physical meanings.

And it's really rare to directly do 2dconv to disparity map,maybe you can give me a straightforward answer why it can improve the accuracy of prediction.

Thanks.

**Comment by AlessioTonioni** [comment]
We have followed design choices similar to the *contextual network* of PWC (https://arxiv.org/pdf/1709.02371.pdf). 

The idea is to provide the current best prediction of the model (the disparity) and a learned representation of the input (the left features). I agree that different fusion strategies might be possible, but we have not spend much time investigating them as the current solution was already providing reasonable results.
