### ISSUE TITLE
Failed to reproduce the reported results on Middlebury Motorcycle.

### ISSUE THREAD

**Issue by skmhrk1209** [CVLAB-Unibo/Real-time-self-adaptive-deep-stereo#35]
Hi, thanks for sharing the code.

In my experiments on Middlebury Motorcycle, I could not reproduce the reported result  even when using full adaptation.
To force invalid disparity to zero, I addded the following line to Stereo_Online_Adaptation.py.
``` python
# line 46
gt_image_batch = tf.where(tf.is_finite(gt_image_batch), gt_image_batch, tf.zeros_like(gt_image_batch))
```

|Adaptation|D1-all [%]|EPE|
|-----------|---------|----|
|MAD (lr=1e-4)|81.62|26.47|
|MAD (lr=1e-5)|42.79|13.79|
|FULL (lr=1e-4)|85.39|25.60|
|FULL (lr=1e-5)|41.91|13.95|

Tab 1. Results on Middlebury Motorcycle using the model trained on synthetic dataset (you provided).

<img src="https://user-images.githubusercontent.com/29158616/70044456-bf65f880-1605-11ea-96c5-163cad2a2400.png" width="500">

![EPE](https://user-images.githubusercontent.com/29158616/70042509-4f09a800-1602-11ea-891c-806e9d1e8c47.png)
Fig 1. EPE curve on Middlebury Motorcycle.

![bad3](https://user-images.githubusercontent.com/29158616/70042576-76607500-1602-11ea-9ecb-2bc72bf462d8.png)
Fig 2. D1-all curve on Middlebury Motorcycle.

Should I modify the other parameters? Thank you.

**Comment by AlessioTonioni** [comment]
Hi,
I have re-run the tests with this version of the code and I get a similar trend to the one in the paper except for the initial EPE that it's higher. I'm not sure if in the test in the paper we were using a central crop of the image or a slightly different rescale.

Anyway, at this link you can find my results, the images I have used and the command line to reproduce everything.
https://drive.google.com/open?id=1NvWeQnTf6TjDXFwPhgC6pK30T1zWh6hu

**Comment by skmhrk1209** [comment]
Thank you for providing the scripts.
I used quarter resolution of originals like your script, and got roughly the same results as the paper.
