### ISSUE TITLE
how can i run Stereo_Online_Adaptation.py

### ISSUE THREAD

**Issue by chy132** [CVLAB-Unibo/Real-time-self-adaptive-deep-stereo#37]
thanks for your code!
here is my question, when i first use Stereo_Online_Adaptation.py, i have set the list, ouuput as follows:
parser.add_argument("-l","--list", help='path to the list file with frames to be processed', default='D:\zed\python\depth\Real-time self-adaptive deep stereo\Real-time-self-adaptive-deep-stereo-master\ex_list.csv',required=True)
	parser.add_argument("-o","--output", help="path to the output folder where the results will be saved", default=r'D:\zed\python\depth\Real-time self-adaptive deep stereo\Real-time-self-adaptive-deep-stereo-master\output/', required=True)
	parser.add_argument("--weights",help="path to the initial weights for the disparity estimation network",default=r'D:\zed\python\depth\Real-time self-adaptive deep stereo\MADNet\kitti\weights.ckpt',required=True)
	parser.add_argument("--modelName", help="name of the stereo model to be used", default="MADNet", choices=Nets.STEREO_FACTORY.keys())
	parser.add_argument("--numBlocks", help="number of CNN portions to train at each iteration",type=int,default=1)
	parser.add_argument("--lr", help="value for learning rate",default=0.0001, type=float)
	parser.add_argument("--blockConfig",help="path to the block_config json file",default=r'D:\zed\python\depth\Real-time self-adaptive deep stereo\Real-time-self-adaptive-deep-stereo-master\block_config/MadNet_full.json',required=True)

but there is a problem:Stereo_Online_Adaptation.py: error: the following arguments are required: -l/--list, -o/--output, --weights, --blockConfig
An exception has occurred, use %tb to see the full traceback.

how can do for it?

**Comment by AlessioTonioni** [comment]
I never test it on windows but I guess that the problem might be the use of '\\', try to sue '\\\\'
