### ISSUE TITLE
Understanding disparity prediction scaling

### ISSUE THREAD

**Issue by miloknowles** [CVLAB-Unibo/Real-time-self-adaptive-deep-stereo#41]
I'm re-implementing MadNet in Pytorch, and having trouble understanding the scaling you use for disparity predictions. In particular, in ```make_disp```:

```python
def _make_disp(self,op,scale):
    op = tf.image.resize_images(tf.nn.relu(op * -20), ...
```

It seems that by design, each disparity module is outputting disparity in units of 1/20th of a pixel at full resolution, which you then rescale to pixels by multiplying by 20. I'm confused why the negative sign is there - I'm assuming it has to do with converting disparity from left to right or vice-versa?

If that's true, training with the ```nn.relu``` should force the network to learn negative disparities inside of ```op```. Do you interpret the ```real_disp_vi``` outputs in your code as left or right disparity images?

Thanks for sharing your code, I'm looking forward to using the network!

**Comment by AlessioTonioni** [comment]
> It seems that by design, each disparity module is outputting disparity in units of 1/20th of a pixel at full resolution, which you then rescale to pixels by multiplying by 20. I'm confused why the negative sign is there - I'm assuming it has to do with converting disparity from left to right or vice-versa?

The scaling by 20 is a trick that seems to stabilize training but I have no clear explanation on why it is supposed to work, in the end is just a constant scaling which should not affect anything in particular in the network. if I remember well we took the idea from the Flownet2 paper. As for the - we took it from the original Dispnet implementation. Again in the end it shouldn't change much in the convergence of the network, but empirically it seems to help.

The disparity predicted are aligned with the left image and a positive value means that to get to the right pixel you have to shift left by that amount of pixels.

**Comment by miloknowles** [comment]
Thanks so much, I think this fixes the issues I was having! I wasn't thinking and assumed that you should have to shift *right* in the right image to get the corresponding pixel - this forced the network to learn negative disparities, but those were being set to zero due to the ReLUs. After a few training batches, disparity was zero everywhere.
