### ISSUE TITLE
How can I save and use the adapted weights 

### ISSUE THREAD

**Issue by YJonmo** [CVLAB-Unibo/Real-time-self-adaptive-deep-stereo#42]
Thanks for this great work.

I have trained the network on the simulated data and also later on I used the adaptive mode to get the depth for my real stereo images (clean images). What I am interested is to save the adapted weights and then use them later or in a nonadaptive set up, because my stereo images are noisy so I cannot not use the adaptive mode all the time. Is that possible?

Regards,
Jacob

**Comment by AlessioTonioni** [comment]
To save he weights you should modify `Stereo_Online_Adaptation.py` to explicitly save the model parameters when you want (e.g., at the end of the adaptation steps). You cna use something similar to what we are doing in `Train.py`
https://github.com/CVLAB-Unibo/Real-time-self-adaptive-deep-stereo/blob/dd6d0ff082d0efa136dd3c8dd392eb510ca70fdb/Train.py#L153

Once saved as ckpt files, you can reload the weights providing a path to the file to the script with the `--weights` flag
