### ISSUE TITLE
Some questions about cost volume

### ISSUE THREAD

**Issue by Yzmblog** [CVLAB-Unibo/Real-time-self-adaptive-deep-stereo#44]
May i ask you that how did you connect the left and right feature to get the cost volume? In which dimension specifically? And i saw your code didn't use 3dCnn , is that correct?
I would appreciate it if you could answer what confusing me.Thanks.

**Comment by mattpoggi** [comment]
Hi @Yzmblog ,
we use 1D correlation layers (http://openaccess.thecvf.com/content_cvpr_2016/papers/Mayer_A_Large_Dataset_CVPR_2016_paper.pdf), computing correlation between features and stacking them in the channel dimension.

**Comment by Yzmblog** [comment]
@mattpoggi 
oh，I get it, thanks so much!
