### ISSUE TITLE
how to train on multi-GPU

### ISSUE THREAD

**Issue by zhzxlcc** [CVLAB-Unibo/Real-time-self-adaptive-deep-stereo#45]
Excuse me, could I retrain your model on multi-GPU simply by os.environ["CUDA_VISIBLE_DEVICES"]="4,5"? Or adding the gradient towers?  Because the one GPU is out of memory. Thanks a lot.

**Comment by AlessioTonioni** [comment]
Hello,
The current code does not suppport multi gpus training since the network was trained on single GTX 1080 ti. 
It should be feasible to modify it to support multi gpus training following the official guidelines on the tensorflow website

**Comment by zhzxlcc** [comment]
Ok, I see. Thanks for your guidance.
