### ISSUE TITLE
Does the self-adaptive network support unrectified stereo image?

### ISSUE THREAD

**Issue by yaobaishen** [CVLAB-Unibo/Real-time-self-adaptive-deep-stereo#47]
From the paper I read that **domain shift** is a remarkable work to adapt the model during online running. So is it possible to feed the network with raw stereo image pairs without calibration?
My question is, if the adapting ability is strong enough, even we feed raw image pairs, could the network be able to continuously fine-tune the disparity to a good state?

**Comment by AlessioTonioni** [comment]
No the architecture relies on explicit correlation layers that expects rectified images as input. A correlation layer search for corresponding features between two views along horizontal epipolar lines assuming that the images have been rectified. If the images are not rectified the correlation layers will fail badly and therefore the whole network will do the same. 
If you want to work with unrectified or badly rectified images is probably better to look at optical flow architectures and discards the vertical component of the flow.

**Comment by yaobaishen** [comment]
I see. I have this question because the mechanical design of stereo camera should be very solid, but we still need to re-do the calibration time to time due to vibration or other environment changes. It would be very great if the self adapting work could work on unrectified stereo images.

**Comment by yaobaishen** [comment]
Close it, thanks for reply.
