### ISSUE TITLE
ZED disparity quality issue

### ISSUE THREAD

**Issue by yaobaishen** [CVLAB-Unibo/Real-time-self-adaptive-deep-stereo#48]
Thanks for providing the Live_Adaptation_Demo.py and luckily I have a first generation ZED camera, not the ZED_mini. After some simple modifications of the grabber.py, I can run the demo online with ZED images (720P@30fps), but the disparity looks not good and is very unstable. Here are the steps:
1. launch the demo indoor;
2. move the ZED camera around my office to gather enough images for the model adapting;
3. wait 3 to 5 minutes, so there are about 5000~8000 images which have been send to the network;
4. the disparity is still not good.
So, do I MUST use the ZED_mini camera? I think the baseline difference is not very big.
Or is there some extra work I need to do? Thanks.

**Comment by yaobaishen** [comment]
here is the command line:
```
python3  Live_Adaptation_Demo.py  --weights ../pretrained_nets/MADNet/synthetic/weights.ckpt
```

**Comment by AlessioTonioni** [comment]
run 
`python 3 Live_Adaptation_Demo.py -h` 
to check all the available command line options and their default value. 

In particular the `--mode` flag sets the adaptation strategy to use and defaults a `NONE` therefore if you don't set it properly the code is not running in adaptation mode but only inference.

Try to add `--mode FULL`

**Comment by yaobaishen** [comment]
I have a try the
```
--mode FULL
```
option and the disparity has noticeable improvement, I need some time to do the evaluation and will update here, cheers ~
