### ISSUE TITLE
how to integrate other network to this self adaptive framework?

### ISSUE THREAD

**Issue by passion3394** [CVLAB-Unibo/Real-time-self-adaptive-deep-stereo#49]
such as PSMNet, GANet?

**Comment by AlessioTonioni** [comment]
You should implement the network and wrap it in a class that inerhits from [`Stereo_net.py`].(https://github.com/CVLAB-Unibo/Real-time-self-adaptive-deep-stereo/blob/master/Nets/Stereo_net.py)

Something similar to what has been done for MadNet in [`MadNet.py`](https://github.com/CVLAB-Unibo/Real-time-self-adaptive-deep-stereo/blob/master/Nets/MadNet.py) and Dispnet in [`DispNet.py`](https://github.com/CVLAB-Unibo/Real-time-self-adaptive-deep-stereo/blob/master/Nets/DispNet.py)

Finally add the network class to the factory method in [`Nets/__init__.py`](https://github.com/CVLAB-Unibo/Real-time-self-adaptive-deep-stereo/blob/master/Nets/__init__.py)

**Comment by passion3394** [comment]
thanks for your reply.
