### ISSUE TITLE
Division by zero error

### ISSUE THREAD

**Issue by sarimmehdi** [CVLAB-Unibo/Real-time-self-adaptive-deep-stereo#53]
Hello. I get the following error when trying to run Stereo_Online_Adaptation.py:

```
Traceback (most recent call last):
  File "Stereo_Online_Adaptation.py", line 325, in <module>
    main(args)
  File "Stereo_Online_Adaptation.py", line 267, in main
    f_out.write('time,{},{}\n'.format(exec_time,exec_time/step))
ZeroDivisionError: division by zero
```
I use your instructions to run Stereo_Online_Adaptation.py:

```
LIST=IMG_LIST.csv
OUTPUT="/mnt/sdb1/datasets/kitti_detection/training/depth_maps_0_to_100"
WEIGHTS="weights.ckpt"
MODELNAME="MADNet"
BLOCKCONFIG="block_config/MadNet_full.json"

python Stereo_Online_Adaptation.py     -l ${LIST}     -o ${OUTPUT}     --weights ${WEIGHTS}     --modelName MADNet     --blockConfig ${BLOCKCONFIG}     --mode MAD     --sampleMode PROBABILITY     --logDispStep 1
```

I am using the pre-trained weight provided by you. Please tell me why I am getting this error. Thank you.

**Comment by AlessioTonioni** [comment]
Your execution exit from the `while True` loop defined at line 178 right away, therefore step is = 0 and this cause the exception you are seeing. 
If I have to guess I would say that something is wrong with the data reading pipeline. 
What kind of data are you trying to read? 
What is the content of ${LIST}?

**Comment by sarimmehdi** [comment]
Thank you for your reply. Actually, I have a 4GB GPU (GTX 1050Ti) which is not enough to run this. So, that piece of code doesn't execute.
