### ISSUE TITLE
Speed on TX2

### ISSUE THREAD

**Issue by MJITG** [CVLAB-Unibo/Real-time-self-adaptive-deep-stereo#54]
Hi, @AlessioTonioni ,
I'm reading your paper. In the last paragraph, MADNet runs up to 0.26s in tx2 with the same optimization level with StereoNet. Is there a more detailed configuration?

**Comment by AlessioTonioni** [comment]
@mattpoggi for the details.

**Comment by MJITG** [comment]
@mattpoggi

**Comment by MJITG** [comment]
Hi, I failed to load the weights file. I get `Failed to find any matching files for WEIGHTS` error.
Here's m script:
`#!/usr/bin/env bash
set -x

OUTPUT="/data/daihe_data/Real-time-selaf-adaptive-stereo-master/"
WEIGHTS="/data/daihe_data/MADNet-weights/MADNet/kitti"
MODELNAME="MADNet"
BLOCKCONFIG="block_config/MadNet_full.json"

CUDA_VISIBLE_DEVICES=9 python3 Stereo_Online_Adaptation.py \
    -l example_list.csv \
    -o ${OUTPUT} \
    --modelName MADNet \
    --blockConfig ${BLOCKCONFIG} \
    --mode NONE \
    --sampleMode PROBABILITY \
    --logDispStep 1 \
    --weights WEIGHTS`

**Comment by AlessioTonioni** [comment]
you need to expand the variable in bash

```
#!/usr/bin/env bash
set -x

OUTPUT="/data/daihe_data/Real-time-selaf-adaptive-stereo-master/"
WEIGHTS="/data/daihe_data/MADNet-weights/MADNet/kitti/weights.ckpt"
MODELNAME="MADNet"
BLOCKCONFIG="block_config/MadNet_full.json"

CUDA_VISIBLE_DEVICES=9 python3 Stereo_Online_Adaptation.py \
    -l example_list.csv \
    -o ${OUTPUT} \
    --modelName MADNet \
    --blockConfig ${BLOCKCONFIG} \
    --mode NONE \
    --sampleMode PROBABILITY \
    --logDispStep 1 \
    --weights ${WEIGHTS}
```
