### ISSUE TITLE
How to reverse the intensity in your depth image (points farther away should appear brighter and closer points should appear darker)

### ISSUE THREAD

**Issue by sarimmehdi** [CVLAB-Unibo/Real-time-self-adaptive-deep-stereo#55]
Hello. I am using the formulas for converting depth map to lidar as proposed in the Pseudo-LIDAR paper [https://arxiv.org/pdf/1812.07179.pdf](url) but I am getting really bad results. I have mentioned that issue over there too: [https://github.com/mileyan/pseudo_lidar/issues/45](url)

Do you know why this might be happening?

Edit: After looking at Pseudo-LIDAR code I have realized that this might be happening because depth is directly proportional to pixel intensity. So, I guess I wanted to know, how to reverse the pixel intensity in your generated disparity map? Meaning closer pixels should appear darker (less pixel value corresponding to less depth) and pixels that are far away should appear brighter (high pixel value corresponding to high depth). I tried subtracting each pixel value from 255 but that just made the whole image very bright

**Comment by AlessioTonioni** [comment]
disparity is not depth.

` depth = (baseline * focal) / disparity`

**Comment by sarimmehdi** [comment]
Thank you. I actually realized my confusion before you replied. I will close this now, thank you
