### ISSUE TITLE
Camera Config json

### ISSUE THREAD

**Issue by Dazworth** [CVLAB-Unibo/Real-time-self-adaptive-deep-stereo#60]
Hi guys,
Just wondering what the camera config json should consist of for implementing the live adaptation demo? I have a ZED 2 and ZED camera available so can use either, thank you

**Comment by AlessioTonioni** [comment]
The loading and decoding of the config file is here:
https://github.com/CVLAB-Unibo/Real-time-self-adaptive-deep-stereo/blob/e630bc610c134d348c8c15e660533b2f464bba5f/Demo/grabber.py#L119
the only two fields used are:
```
        if 'resolution' in self._config:
            self._params.camera_resolution = self._key_to_res[self._config['resolution']]
        else:
            self._params.camera_resolution = sl.RESOLUTION.RESOLUTION_HD720
        
        if 'fps' in self._config:
            self._params.camera_fps = self._config['fps']
        else:
            self._params.camera_fps = 30
```
As you can see you can also pass an empty config and it should default to 720p for resolution and 30fps.
