### ISSUE TITLE
A warning about 'get_proxy_loss' in Stereo_Continual_Adaptation.py

### ISSUE THREAD

**Issue by rimianxing** [CVLAB-Unibo/Real-time-self-adaptive-deep-stereo#79]
Thanks for your brilliant work!
I've noticed that you might forget to upate the loss_factory.py, as there is a warning at line 75 and line 112 in Stereo_Continual_Adaptation.py, "Cannot find reference 'get_proxy_loss' in 'loss_factory.py' ".

**Comment by mattpoggi** [comment]
Thanks, it was missing! I've just added it now
