### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by RayWuuuuu** [CVLAB-Unibo/Real-time-self-adaptive-deep-stereo#9]
Hi, I want to run the pre-trained model, and I downloaded from the link you provided, but I found no checkpoint archives in the pre-trained folder, can you provide your checkpoint archives,thank you so much!

**Comment by AlessioTonioni** [comment]
Just run the scripts with
`--weights ${PATH_TO_DOWNLOAD_FOLDER}/MADNet/synthetic/weights.ckpt` 
to load the weight of MADNer trained on F3D.

The folder contains three files named `weights.ckpt` + different extensions, but don't worry because the tensorflow API should successfully load the weights.

**Comment by RayWuuuuu** [comment]
Thank you so much for your help!
